services:
  # Web Service
  - type: web
    name: camts-pos
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: CAMTS-POS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: camts-pos-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

databases:
  # PostgreSQL Database
  - name: camts-pos-db
    databaseName: camts_pos
    user: camts_user